version: '3.9'

services: 
  db:
    image: postgres
    restart: always
    ports: 
      - 127.0.0.1:5432:5432
    environment: 
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: journal
    volumes:
      - ./data:/var/lib/postgresql/data
