version: '3.9'

services: 
  services:
  web:
    build:
      context: ./journal             # Путь к Dockerfile
    ports:
      - "8000:8000"                  # Проброс порта для веб-приложения
    depends_on:
      - db                           # Сначала запускается база данных
    environment:
      DATABASE_URL: postgres://example_user:example@db:5432/journal
      # Формат: postgres://<пользователь>:<пароль>@<хост>:<порт>/<база данных>

  db:
    image: postgres
    restart: always
    ports: 
      - 127.0.0.1:5432:5432
    environment: 
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: journal
    volumes:
      - ./data:/var/lib/postgresql/data
